### PR TITLE
Create ability for user to add and view work experience

### LINKED ISSUE #11: Page for adding a new Experience
Add a page that allows users to add a new Experience which includes the following fields:

- title
- company
- start_date
- end_date
- description
- logo

Collaborate with the fellows contributing to the Python project to understand how logos will be managed. For now, assume this is a string (URL to the image). 

When this information is submitted, a POST request should be made to `/resume/experience` on the server in the following format:

```json
{
    "title": "Software Developer",
    "company": "A Cooler Company",
    "start_date": "October 2022",    
    "end_date": "Present",
    "description": "Writing JavaScript Code",
    "logo": "example-logo.png",
}
```

The server will return a JSON with the position in the list in the following format:
```json
{
"id": 1
}
```

### PR DESCRIPTION
**Pull request by citruscai**
Fixes  #11
#### 1. **`ExperienceForm` Component**
   - **Form Fields**: Users can input details about their professional experiences, including:
     - **Title**: The role or position held.
     - **Company**: The name of the company.
     - **Start Date**: The date the experience began.
     - **End Date**: The date the experience ended (or mark it as "Present" for current roles).
     - **Description**: A detailed description of responsibilities and achievements.
     - **Logo Upload**: Allows users to upload a company logo, which is then previewed within the form.
   - **Input Validation**:
     - Title, Company, and Start Date are required fields.
     - The End Date cannot be earlier than the Start Date.
     - Users can check "Current Job," which will replace the End Date with "Present."
   - **Responsive Design**: The form adjusts to various screen sizes, with aligned inputs and centered logo upload.
   - **Error Handling**: Displays validation messages for incorrect date ranges.

#### 2. **`ViewExperience` Component**
   - **Displays Experiences**: Lists all the experiences added through the `ExperienceForm` in a table-like structure.
   - **Sorting**:
     - Experiences marked as "Present" (current roles) are prioritized at the top.
     - The remaining experiences are ordered in descending order by the start date (latest to earliest).
   - **Action Buttons**: Each experience entry includes:
     - **Edit Button**: For future implementation of editing functionality.
     - **Delete Button**: For future implementation of deleting functionality.
   - **Company Logo**: Displays the uploaded logo for each experience. If no logo is provided, a placeholder "No Logo" message is displayed.
   - **Responsive Layout**: The layout adapts for different screen sizes, with columns for logo, experience details, and action buttons.
Screenshot 2024-10-02 171411
Screenshot 2024-10-02 171749

### CODE REVIEW

**Review by yashika51 — CHANGES_REQUESTED** [review]
can you please make sure the tests are passing before we approve this for merge?

**Comment by Kingscliq** [comment]
This is pretty decent @citruscai , excellent job.

My thoughts:

1. yarn lock should be added to gitignore
2. There is a prettier config file, but  there is no configuration so that we all share the same config and formatting
3. The summary view is so neatly designed but it's not responsive on mobile view
4. for consistency I would have preferred we have created custom components like form fields, and modals, so anyone can pick it up and reuse

But overall you did a great job. Kudos!

**Comment by yashika51** [comment]
> This is pretty decent @citruscai , excellent job.
> 
> My thoughts:
> 
> 1. yarn lock should be added to gitignore
> 2. There is a prettier config file, but  there is no configuration so that we all share the same config and formatting
> 3. The summary view is so neatly designed but it's not responsive on mobile view
> 4. for consistency I would have preferred we have created custom components like form fields, and modals, so anyone can pick it up and reuse
> 
> But overall you did a great job. Kudos!

Agreed with @Kingscliq, @citruscai please look into these points

**Comment by citruscai** [comment]
thank you so much @Kingscliq @yashika51 !! will look into it! will hopefully have these fixes in by end of day

**Comment by citruscai** [comment]
@Kingscliq should i remove it from my committ? this article is suggesting to keep it in git and the only reason it was in my commit was because of the prettier formatting https://github.com/yarnpkg/yarn/issues/1583

**Comment by Kingscliq** [comment]
> @Kingscliq should i remove it from my committ? this article is suggesting to keep it in git and the only reason it was in my commit was because of the prettier formatting [yarnpkg/yarn#1583](https://github.com/yarnpkg/yarn/issues/1583)

You can leave it. it's unopinionated. But I agree with the article for sharing consistent packages across projects

**Comment by citruscai** [comment]
**Changes Made:**
- **Converted Experience Form to Modal**: The `ExperienceForm` component has been changed to modal to maintain consistency in application and both mobile and browser views - shoutout to  @Kingscliq for pointing that out, in previous projects i didnt check t
- **Implemented Test Cases**: Comprehensive test cases have been added for the `ExperienceForm` to ensure its functionality:
  - Verified rendering and user input for job title, company, and dates.
  - Tested behavior for the current job checkbox, including updating the end date to "Present" when checked.
  - Ensured the cancel button correctly invokes the `onCancel` callback and that the form does not submit with invalid end dates.
  
Made sure its passing all checks! should be good to go
@yashika51 does it look good? 😄

**Comment by citruscai** [comment]
@yashika51  ok just fixed conflicts and workflow checks  all passing now

**Comment by yashika51** [comment]
> **Changes Made:**
> 
> * **Converted Experience Form to Modal**: The `ExperienceForm` component has been changed to modal to maintain consistency in application and both mobile and browser views - shoutout to  @Kingscliq for pointing that out, in previous projects i didnt check the mobile view of components. that is very important
> * **Implemented Test Cases**: Comprehensive test cases have been added for the `ExperienceForm` to ensure its functionality:
>   
>   * Verified rendering and user input for job title, company, and dates.
>   * Tested behavior for the current job checkbox, including updating the end date to "Present" when checked.
>   * Ensured the cancel button correctly invokes the `onCancel` callback and that the form does not submit with invalid end dates.
> 
> Made sure its passing all checks! should be good to go @yashika51 does it look good? 😄

Good job!

**Pull request merged**
